// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types.merged";

const SUPABASE_URL = "https://porkdpuntvtbloybtwnh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBvcmtkcHVudHZ0YmxveWJ0d25oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI0Nzk3MTIsImV4cCI6MjA4ODA1NTcxMn0.Ch2v0OzsTWgRqk5OIeIHgtgGBtQKpDgxX4HRFCRY6og";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
